### ISSUE TITLE
parameter sweep docs not currently built

### ISSUE THREAD

**Issue by ceball** [pyviz-topics/EarthSim#113]
[EDIT: changed title because we're going to skip parameter sweeps from the docs temporarily; see https://github.com/pyviz/EarthSim/issues/113#issuecomment-399935116 ]

@jlstevens, should topics/GSSHA_Parameter_Sweep be part of the website, and if so, in its current form? I ask because travis runs out of disk space while executing it. I could skip it, or figure out how to get more disk space (it's possible). Who knows, maybe if travis didn't run out of disk space while running this notebook, it would just happen while running another. (Which is why I'm asking if you expect topics/GSSHA_Parameter_Sweep to be part of the automatically-generated-on-travis website in its current form, or if you expect that notebook would cause a problem.)

**Comment by kcpevey** [comment]
@sdc50 was working on the GSSHA workflows. Not sure if that one was included or not.

**Comment by sdc50** [comment]
I haven't pushed anything yet, and was only working on the non-parameter-sweep workflow. However, both workflows probably download data that could be cleaned up after they are processed. That might help with the disk space issue.

**Comment by jlstevens** [comment]
> ... should topics/GSSHA_Parameter_Sweep be part of the website, and if so, in its current form?

I don't think that notebook should be part of the website. It is just an example of the sort of workflow I'll be developing for Amanda.

**Comment by jbednar** [comment]
*Something* delivering this functionality should be part of the website; seems like this one at least makes use of what we already have to have available to build the website, whereas some other parameter sweeping would be some new set of dependencies that we may not want to pull in.  So I would vote for making it be part of the website, trimming it down if need be; any other future example seems speculative and can be dealt with at that time.

**Comment by jlstevens** [comment]
> ... seems like this one at least makes use of what we already have to have available to build the website, whereas some other parameter sweeping would be some new set of dependencies that we may not want to pull in. 

I suppose that is true, it is based on something we already have. I don't know what to suggest about the travis disk space issue as I don't know how to reduce the disk space requirements.

**Comment by ceball** [comment]
I think initially we'll do something like just show the gssha parameter sweep notebook without running it. After that, we can figure out how to run it in a reasonable way.

(The reason not to just do the latter immediately is something like...it downloads something large that's not currently parameterized/under our control. I don't remember exactly.)

**Comment by kcpevey** [comment]
Plan is to remove GSSHA from the project examples and replace with AdH examples
