### ISSUE TITLE
Touch screen controls

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#122]
Where do the touch screen controls for Windows for drawings sit? I noticed a couple usability things that are not real issues, but if its not a big deal, may improve interaction.  
 
* [ ]  Two-finger zoom is REALLY sensitive
* [ ] If user starts two-finger zoom in, any additional finger movement results in further zooming in. If you don't pick up your hand, you cannot zoom back out. I.e. you can't zoom in and zoom back out without lifting your fingers from the screen. Its not intuitive.

**Comment by philippjfr** [comment]
This would have to be raised at the bokeh level but my immediate impression is that this may not be easy to improve. Bokeh interactions are built on [hammerJS](http://hammerjs.github.io/), which provides the touch capabilities out of the box.

**Comment by kcpevey** [comment]
Closing for now since its outside of the current scope.
