### ISSUE TITLE
Tile service repeating

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#123]
There is a maximum level to which I can zoom out when I have a tile service loaded. That's good. My data is projected onto the tile service in the proper location. When I zoom out past the extents of the world, the tile service repeats itself. If I have data loaded on top of the tiles, its not always apparent which instance of the world tile service contains my data. I'm wondering, if there is a max extents on the tile service, would it be easy to just set those to the max extents of the tile service? If the answer is no, then I'll leave this alone because the reset button works well enough.  
  
![tile_service](https://user-images.githubusercontent.com/15659110/41563724-1bbb6ad2-7316-11e8-936d-aef83492e123.PNG)

**Comment by philippjfr** [comment]
We have plans to restrict the range to which you can zoom out to avoid this kind of thing.

**Comment by kcpevey** [comment]
@philippjfr Can I get a status update on this?

**Comment by philippjfr** [comment]
Hard-bounds on axis ranges are still not implemented but we can try to prioritize them if this is a big deal for you.

**Comment by kcpevey** [comment]
This is low priority. I'd say it falls into the category of 'nice to have' but not 'required'. I'll leave it open as a reminder if we have time later.

**Comment by philippjfr** [comment]
Going to close this since I opened this issue in GeoViews now https://github.com/pyviz/geoviews/issues/324
