### ISSUE TITLE
Quadmesh slow

### ISSUE THREAD

**Issue by hetland** [pyviz-topics/EarthSim#151]
Quadmesh rendered in geoviews is quite slow (though correct) with a small sized dataset. The rendering -- zooming and panning on the map -- seems too slow for the size of the dataset. The dask workers are not used, though should be.

    import geoviews as gv
    import holoviews as hv
    from holoviews.operation.datashader import datashade
    from dask.distributed import Client
    import xarray 
    hv.extension('bokeh')
    
    client = Client()
    da = xarray.open_dataset('test_quadmesh.nc', chunks={})
    tiles = (gv.tile_sources.OSM).options(width=900, height=500)
    
    salt = da.salt.sel(ocean_time='2016-08-01 10:00').isel(s_rho=-1).data
    lon = da.lon_rho.data
    lat = da.lat_rho.data
    saltmesh = gv.QuadMesh((lon, lat, salt))
    
    tiles * datashade(saltmesh)

The small dataset used can be found here:

https://www.dropbox.com/s/dfqxkkhab699yxk/test_quadmesh.nc?dl=0

**Comment by jbednar** [comment]
Alas yes; see https://github.com/bokeh/datashader/issues/598 .

**Comment by philippjfr** [comment]
Optimized QuadMesh rendering has now been merged into Datashader and HoloViews.
