### ISSUE TITLE
vertex_table point selection visualization

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#156]
When I have a row highlighted in the vertex_table, I'd like to visually see what point that is in the drawing tool. The viz behavior should be the same as if I were using the PointDraw tool and had a point selected (alpha values applied to everything upon selection).

**Comment by philippjfr** [comment]
Already started prototyping this, the main issue currently is how it interacts with the vertices created by the PolyEditTool.

**Comment by kcpevey** [comment]
@philippjfr was this ever implemented? I'm not seeing it in my current notebooks, but I've been having issues with my tables so it might just be me.

**Comment by philippjfr** [comment]
This **should** be working, if you're still seeing issues with the tables then we should file explicit issues for those and address them.
