### ISSUE TITLE
Additional CI builds to enable

### ISSUE THREAD

**Issue by ceball** [pyviz-topics/EarthSim#170]
* [ ] windows dev (currently only windows user is tested; see #167)
* [ ] unpinned c-f (indication of upcoming compatibility issues; see #168)

**Comment by ocefpaf** [comment]
> unpinned c-f (indication of upcoming compatibility issues; see #168)

Please feel free to ping me on the issue you find while doing that.
I'll work on the missing packages soon to make that easier and I'll ping on the PRs I send to `conda-forge`.
