### ISSUE TITLE
Add busy indicator for bokeh based dashboards

### ISSUE THREAD

**Issue by philippjfr** [pyviz-topics/EarthSim#177]
When working with a complex dashboard which triggers some computation on the server you frequently want to indicate that the server is busy processing a previous event to provide the user some visual feedback. Currently there is no easy way to do this, but there might be a few workarounds until this is properly implemented in bokeh (see https://github.com/bokeh/bokeh/issues/3393).

Some suggestions might include:

* Write a CustomJS script to change the cursor
* Add an element to indicate progress and trigger an immediate stream event before the compute heavy task is launched

**Comment by kcpevey** [comment]
We are comfortable with the spinner.gif workaround. It can be revisited https://github.com/bokeh/bokeh/pull/8823 is merged to ensure that it fits our needs.
