### ISSUE TITLE
Need support for custom icons for Bokeh tools

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#178]
We need a way to distinguish between the `PolyEdit` used for denoting foreground and background in Grabcuts. Since this implementation of Grabcuts results in a polygon, the two tool icons need to have some indication whether you are intending to mark up the inside of the polygon or the outside. I was doodling yesterday and came up with the two icons below, but I'm sure someone can improve upon it!  
  
![grabcut_icons](https://user-images.githubusercontent.com/15659110/43844561-a9220f06-9aef-11e8-9f86-7ccd1ed91eb4.png)
I guess I should also note that I intend for the default drawing tool for Grabcuts to use the scibble draw.

**Comment by jbednar** [comment]
Those icons should work fine, though they would be custom to EarthSim, since they are specific to GrabCut.  @philippjfr, are custom icons like that supported yet?

**Comment by jlstevens** [comment]
From my understanding such custom icons aren't yet supported at the bokeh level though @philippjfr can correct me if that isn't true...

**Comment by kcpevey** [comment]
custom icons are now available at the bokeh level
