### ISSUE TITLE
Inconsistent poly_stream column labels before and after viz

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#213]
Before a stream is visualized, the `data` columns include the location data as `Latitude` and `Longitude`. 
```
annot.poly_stream
PolyDraw(data={'Longitude': [array([-10114986., -10123906., -10130333., -10121522., -10129889.,
       -10122959.])], 'Latitude': [array([3806790., 3812413., 3807530., 3805407., 3798394., 3796693.])]})
```
After the stream is visualized, the `data` columns include the location data as `xs` and `ys`:
```
PolyDraw(data={'xs': [array([-10114986., -10123906., -10130333., -10121522., -10129889.,
       -10122959.])], 'ys': [array([3806790., 3812413., 3807530., 3805407., 3798394., 3796693.])], 'Group': array([''], dtype='<U1')})
```
I guess theoretically I shouldn't be accessing `poly_stream` before visualization, but this still seems inconsistent. Is there reasoning behind it?

**Comment by philippjfr** [comment]
>I guess theoretically I shouldn't be accessing poly_stream before visualization, but this still seems inconsistent. Is there reasoning behind it?

No, there isn't. The plotting code uses 'xs' and 'ys' by convention, so this should definitely be fixed.

**Comment by kcpevey** [comment]
Hmm... I wonder if its so that the `poly_tables` that are produced are automatically labeled with something reasonable (Lat/Lon) without user input. After all, now the poly_tables visualize with Plate Carree.
