### ISSUE TITLE
num_objects in annotators

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#234]
How would I set number of points in an annotator to be `num_objects=1`? Since that's specified in PolyDraw, I'm guessing it would either have to be exposed all the way up or I need to create my own annotator?

**Comment by philippjfr** [comment]
I'd suggest exposing that as a parameter on the annotators.

**Comment by kcpevey** [comment]
I was able to do this with my own annotator classes.

**Comment by kcpevey** [comment]
@philippjfr could add this to a PR

**Comment by kcpevey** [comment]
This is completed.
