### ISSUE TITLE
Broken freehand drawing image link on Drawing_Tools.html

### ISSUE THREAD

**Issue by rsignell-usgs** [pyviz-topics/EarthSim#236]
On http://earthsim.pyviz.org/user_guide/Drawing_Tools.html in the "Freehand Drawing" section (can't provide direct link because sections don't have anchors) there is a broken link to  
https://bokeh.pydata.org/en/latest/_images/FreehandDraw.png

I tried to figure out what the correct URL was for this image, but was unable to do so.

![2018-09-24_14-46-09](https://user-images.githubusercontent.com/1872600/45975039-24d95500-c011-11e8-87f2-77844727713a.png)

**Comment by jbednar** [comment]
Thanks!  That should be easy to fix.

Sections do have anchors, e.g. this one is http://earthsim.pyviz.org/user_guide/Drawing_Tools.html#Freehand-Drawing . But it would be nice if that were discoverable! :-)

**Comment by rsignell-usgs** [comment]
I'm happy to submit a PR to fix, but it wasn't clear to me how to build the docs so I could test.  I looked in `geoviews`, but didn't see a `Makefile`.

**Comment by philippjfr** [comment]
Appears to have been fixed.
