### ISSUE TITLE
Packaging: re-evaluate binary incompatibility problems

### ISSUE THREAD

**Issue by ceball** [pyviz-topics/EarthSim#237]
Lack of binary compatibility between and within channels has been a problem for EarthSim, particularly for the geo stack and particularly on linux. The problems have prevented conda packages being released and conda env from being used (both ultimately because of not having enough control over channels, at install/creation time and afterwards). There's been various EarthSim discussion about this (e.g. #104, #168), but there are probably new developments to fill in here about improvements to conda and progress on compatibility between conda-forge and defaults (I'm a little out of touch with the status now). So, I think it would be worth re-evaluating things at some point, and have created this issue as a reminder.

**Comment by jbednar** [comment]
The status from conda-forge is visible at https://conda-forge.org/status. I don't think it's gotten far enough to help us yet, as gdal (random thing I checked) isn't in the "done" category.

**Comment by philippjfr** [comment]
We've now switched back to defining the dependencies properly rather than relying on dependencies.txt. There are still issues but they are platform dependent and no longer arise from mixing conda-forge and default channel packages.
