### ISSUE TITLE
Build has started failing on windows

### ISSUE THREAD

**Issue by ceball** [pyviz-topics/EarthSim#240]
Without any commits to eathsim itself.

bcdb0e45 passed 7 days ago: https://ci.appveyor.com/project/pyviz/earthsim/build/1.0.384
bcdb0e45 failed today: https://ci.appveyor.com/project/pyviz/earthsim/build/1.0.387

Presumably some dependency has changed...

**Comment by kcpevey** [comment]
@philippjfr Is this the same issue we are currently having?

**Comment by philippjfr** [comment]
No, this was resolved, we do have a new one but that is recorded elsewhere and is affecting a number of pyviz repos.
