### ISSUE TITLE
param slider widgets and bounds

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#255]
param.Number, Integer, Range sliders allow softbounds to be set which allow the programmatic setting of the value to be outside of the initial range. However, these sliders don't allow humans interacting ONLY with the slider widget to go outside the range, no matter if its hard or soft.

**Comment by jbednar** [comment]
Right.  This was already an issue with parambokeh, and remains an issue with Panel.

**Comment by kcpevey** [comment]
Is it possible to force it into a text box with type and range checking?

**Comment by kcpevey** [comment]
Closing in favor of https://github.com/pyviz/panel/issues/33
