### ISSUE TITLE
Selection tolerance for annotators

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#257]
I think the tolerance for selecting things in the drawings (i.e. how close to the center of a node do I have to click in order to select it) is too small. I continue to be frustrated by trying to select something and accidentally creating a new thing instead. Then of course I have to select that thing I just accidentally created in order to delete it, which often I don't successfully select and end up creating another.... its a vicious cycle.   
  
Am I the only one?

**Comment by philippjfr** [comment]
The only option I'm aware we have here is increasing the size of the points as the hit testing is performed on the actual point extents.

**Comment by kcpevey** [comment]
> the hit testing is performed on the actual point extents . 
  
Hmm... I'll have to check that out. I don't think that's what I was seeing.

**Comment by kcpevey** [comment]
This still frustrates me as I'd prefer not to include huge points all the time, but I've gotten a little more used to the functionality. I'll close since there's nothing to be done.
