### ISSUE TITLE
Plotting duplicate points in a path/poly

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#259]
Plotting duplicate points in a path/polygon throws my MOST FAVORITE error "None of the available storage backends match the data...."   
  
Is this expected?

**Comment by philippjfr** [comment]
>Plotting duplicate points in a path/polygon throws my MOST FAVORITE error "None of the available storage backends match the data...."

Is this using the latest versions? Definitely not expected in any case.

**Comment by philippjfr** [comment]
Any updates on this? Haven't been able to reproduce this.

**Comment by kcpevey** [comment]
Closing since it hasn't been reproduced.
