### ISSUE TITLE
Update bokeh dependency

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#277]
from `dependencies.txt`: 
>pyviz/label/earthsim::bokeh=1.0.0            # Update when available from conda-forge
  
`pyviz/label/earthsim` and `pyviz` channel in general is still on 1.0.0 but `bokeh` and `conda-forge` channels have moved onto 1.0.3.   
  
Just a note: If the env is built with a forced dependency on 1.0.0 (given the above), then geoviews is installed via `python setup.py develop` from master, the geoviews requirements will force a pip install of the newer version of Bokeh which results in the conda env have two different Bokeh versions - 1.0.0 conda installed and 1.0.3 pip installed from pypi.

**Comment by philippjfr** [comment]
Thanks @kcpevey, we should indeed just bump it to 1.0.3 which also includes some important fixes.

**Comment by kcpevey** [comment]
Closing.
