### ISSUE TITLE
Fiona import fails on Windows earthsim env

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#284]
Followed the installation directions on the earthsim page and received this message:  
  
![image](https://user-images.githubusercontent.com/15659110/51615346-32361b80-1eed-11e9-9ee8-10427fb7931b.png)

**Comment by philippjfr** [comment]
I am seeing very similar issues in the latest GeoViews builds (see https://travis-ci.org/pyviz/geoviews/jobs/482965825), which is currently blocking me from releasing geoviews 1.6.2. This is therefore very high on my list of priorities. I suspect this happened during the migration to gcc7 compilers inside conda-forge, but I haven't gotten any further despite spending half my time on Monday trying to figure this out.

**Comment by kcpevey** [comment]
This issue is resolved.
