### ISSUE TITLE
Filigree ignores large point sizes

### ISSUE THREAD

**Issue by jbednar** [pyviz-topics/EarthSim#29]
It's possible we aren't seeing messages for debugging this, but at least at the moment if we specify a mesh control point with an associated size that exceeds the boundary of the visible area, it's simply ignored.  E.g. these two points have the same size, but only the one with room around it is having any effect:

![image](https://user-images.githubusercontent.com/1695496/37228361-f1501302-23a5-11e8-8930-dfd3ead4002c.png)

Seems to me that people will very often wish to put large sizes near the borders of a polygon, as that's the area of the simulation least core to what's being simulated, so it strikes me as likely to be a problem in practice.  In any case, there should be warnings whenever a user input is being ignored.

**Comment by dharhas** [comment]
Right now we are using a very simple python wrapper to a rudimentary cli wrapper of filigree. Fixing this to get better warnings/error messages will need to wait for the new python wrapping of Filigree that is in the works.

**Comment by jbednar** [comment]
Sure.  On the other hand, I don't *think* this should be an error in the first place; seems like it should just get cropped by the size of the polygon.

**Comment by dharhas** [comment]
Well Filigree is trying to do a constrained delaunay triangulation and is probably throwing out conflicting constraints. Typically, in most hydromodels the boundary spacing constrain is a higher priority. In this case, it can't maintain the boundary constraint and the hard point spacing at the same time. Inside Filigree there are more options on how to mesh that are currently not exposed.

**Comment by jbednar** [comment]
Ah; that makes sense.  Here we're only showing how to do a point spacing, and someone would really be using a boundary constraint in those regions anyway.  So yes, I think it's mainly a matter of having better error/warning messages then.

**Comment by kcpevey** [comment]
Filigree has been superseded by xmsmesh. Closing.
