### ISSUE TITLE
Old conda packages need to be removed

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#290]
We’ve run into a situation of telling someone to ‘install earthsim’ and without any other knowledge, they went here https://anaconda.org/conda-forge/earthsim and installed it. That package is 10 months old. There is also one here https://anaconda.org/ceball/earthsim . How can we get these removed so that we don’t mislead people?   
  
And just in case you've found your way to this issue while looking for a conda package, there currently isn't one. You need to go here http://earthsim.pyviz.org/getting_started/ and follow the instructions.

**Comment by jbednar** [comment]
Good question.  First we should make sure we're not using anything at https://anaconda.org/ceball/repo, then we can have those deleted. 

Then, would you rather us make a new conda-forge package, or delete the old one?

**Comment by kcpevey** [comment]
I thought given the env issues, that conda packaging wasn't possible? Or maybe it is now that @philippjfr is simplifying it?  
  
I would love love love to have a conda package that was up to date!

**Comment by philippjfr** [comment]
We are now finally in a state where we can build and publish packages again. So let's try to get new releases of holoviews, datashader and panel out and then tag EarthSim v1.1.0 asap.

**Comment by kcpevey** [comment]
conda packages are now available.
