### ISSUE TITLE
Getting the values of selected polygon

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#291]
Given:  
```
sample_poly1=dict(
    Longitude = [-10114986, -10123906, -10130333, -10121522, -10129889, -10122959],
    Latitude  = [  3806790,   3812413,   3807530,   3805407,   3798394,   3796693])
sample_poly2=dict(
    Longitude = [-10095762, -10101582, -10104906],
    Latitude  = [  3804189,   3817180,   3799659])
annot = PolyAndPointAnnotator(polys=[sample_poly1, sample_poly2])
annot.panel()
```
How would one go about extracting the polygon data for polygon that has been selected with the `PolyEdit` tool?  
  
Seems like this would be straightforward but I looked into the streams and the links and couldn't figure out how to get which value is selected.

**Comment by kcpevey** [comment]
@philippjfr I don't think I ever figured this out. Is it possible?

**Comment by kcpevey** [comment]
@philippjfr Still trying to figure this out

**Comment by kcpevey** [comment]
This is my first step in the utilization of the path breaking work.

**Comment by philippjfr** [comment]
Can take a look at this today.

**Comment by philippjfr** [comment]
Looking now, sorry for the delay.

**Comment by kcpevey** [comment]
@philippjfr I'd like to set this as highest priority.

**Comment by kcpevey** [comment]
Examples are in the annotator docs
