### ISSUE TITLE
How to force Annotator poly_stream population 

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#304]
With the annotators, the poly_stream (hv.streams.PolyDraw) doesn't get populated until its rendered on the screen. I'm trying to write some tests for pytest that will be programmatic and non-UI. Is it possible to force poly_stream to populate without rendering?

**Comment by kcpevey** [comment]
@philippjfr will publish some pytests for annotators to use as an example

**Comment by kcpevey** [comment]
@philippjfr Did examples ever get pushed? I don't see any.

**Comment by kcpevey** [comment]
test are published

**Comment by philippjfr** [comment]
To be precise they now live in ``./earthsim/tests/test_annotators.py``
