### ISSUE TITLE
Editable dataframes 

### ISSUE THREAD

**Issue by kcpevey** [pyviz-topics/EarthSim#318]
@philippjfr  I have a long-term need for editable param dataframes. There is a panel issue here: https://github.com/pyviz/panel/issues/113  
    
To be clear, its possible to render dataframes in panel, but they are no longer editable param objects. I need to maintain the link back to the param object.

**Comment by kcpevey** [comment]
This is low priority

**Comment by philippjfr** [comment]
Merged into Panel master.
