### ISSUE TITLE
OSError if project directory exists

### ISSUE THREAD

**Issue by PeterDSteinberg** [pyviz-topics/EarthSim#37]
This problem is somewhat related to https://github.com/erdc/quest/issues/37 

```
OSError                                   Traceback (most recent call last)
<ipython-input-3-0248b6b2bc3e> in <module>()
      1 intensities = [128, 256, 512]
----> 2 simulations = {intensity: get_simulation(rain_intensity=intensity) for intensity in intensities}

<ipython-input-3-0248b6b2bc3e> in <dictcomp>(.0)
      1 intensities = [128, 256, 512]
----> 2 simulations = {intensity: get_simulation(rain_intensity=intensity) for intensity in intensities}

<ipython-input-2-d6c12e1e309c> in get_simulation(**params)
     14     sim.model_creator.elevation_grid_path = get_file_from_quest(data_dir, sim.elevation_service, 'elevation', sim.model_creator.mask_shapefile)
     15 
---> 16     model = sim.model_creator()
     17     model.project_manager.setCard('FLOOD_GRID',
     18                                   '{0}.fgd'.format(sim.model_creator.project_name),

/mnt/c/Users/erin/code/build-dir/EarthSim/earthsim/gssha/model.py in __call__(self, **params)
    145     def __call__(self,**params):
    146         p = param.ParamOverrides(self,params)
--> 147         return GSSHAModel(**self._map_kw(p))
    148 
    149 

/mnt/c/Users/erin/code/build-dir/EarthSim/earthsim/gssha/model.py in _map_kw(self, p)
    134 
    135     def _map_kw(self,p):
--> 136         kw = super(CreateGSSHAModel,self)._map_kw(p)
    137         kw['mask_shapefile'] = p.mask_shapefile
    138         kw['grid_cell_size'] = p.grid_cell_size

/mnt/c/Users/erin/code/build-dir/EarthSim/earthsim/gssha/model.py in _map_kw(self, p)
     96         kw['project_directory'] = os.path.abspath(os.path.join(p.project_base_directory, p.project_name))
     97         # Currently allows overwriting existing files
---> 98         os.makedirs(kw['project_directory'],exist_ok=True)
     99         kw['project_name'] = p.project_name
    100         return kw

~/miniconda/envs/earthsim/lib/python3.5/os.py in makedirs(name, mode, exist_ok)
    239             return
    240     try:
--> 241         mkdir(name, mode)
    242     except OSError:
    243         # Cannot rely on checking for EEXIST, since the operating system
OSError: [Errno 22] Invalid argument: '/mnt/c/Users/erin/code/build-dir/EarthSim/examples/topics/vicksburg_parameterized_rain_intensity:128'
```

**Comment by ceball** [comment]
@PeterDSteinberg, do you still have the environment/setup to demonstrate this problem? If so, could you say exactly what `kw['project_directory']` is? Is there a colon in it?

Also, how are you running python? It kind of looks like you might be running python on e.g. linux, with a windows/ntfs filesystem mounted? Or you're running via bash on windows? Or something like that?

However you're running python, is it always the same way? I can imagine a situation where there's a colon in a directory name or file name, and that's ok when you run things one way, but not ok when you run things another way. Although ntfs supports colons in file/directory names, windows does not in general.

(Having said all that, presumably we should be doing something to convert things to valid file/directory names - from the traceback, looks like we're constructing the directory name.)

**Comment by PeterDSteinberg** [comment]
Hi @ceball @jbednar - This is something related to running Ubuntu inside of Windows.  I shouldn't slow you down with this - feel free to close.  It's something in Windows usage of Ubuntu at the `os` module level.

**Comment by ceball** [comment]
Sorry, clicked on close when I was aiming at comment!

Even though you happen to be running in an unusual way, in general we should probably still be doing something to sanitize things we're going to use for file/directory names. So I'd favor leaving this open but maybe changing the title.

**Comment by kcpevey** [comment]
Closing since https://github.com/erdc/quest/issues/37 was closed
