### ISSUE TITLE
Filter displayed glyphs and elements via a table selection

### ISSUE THREAD

**Issue by jlstevens** [pyviz-topics/EarthSim#42]
In addition to allowing dynamic updates by editing table values, it could be very useful to be able to toggle what is shown in the visualization via the table(s).

**Comment by kcpevey** [comment]
This is still a priority for this phase, though there is not an immediate need, so its currently low priority. It will become higher priority after we continue trimesh enhancements.

**Comment by kcpevey** [comment]
This is already possible. When something is selected in the table, the remaining elements are muted via `nonselection_alpha`.
