### ISSUE TITLE
After uploading packages, trigger appveyor and test on windows

### ISSUE THREAD

**Issue by ceball** [pyviz-topics/EarthSim#57]
https://github.com/pyviz/pyct/issues/7

**Comment by ceball** [comment]
To explain 'blocked': can't happen until we can make packages (see #237).

However, I'm doing this work in https://github.com/pyviz/pyviz/pulls/81; once that's merged, and once there are packages for earthsim, that same mechanism can be copied here.

**Comment by kcpevey** [comment]
@philippjfr Can I get an update on packaging?

**Comment by philippjfr** [comment]
Packaging is as easy as pushing a tag, I was waiting on merging the quest and xmsmesh updates before tagging a new release.

**Comment by kcpevey** [comment]
@philippjfr Great! Now sure how I missed that.
