### ISSUE TITLE
Roadmap: Task 4c: HPC installable packages

### ISSUE THREAD

**Issue by jlstevens** [pyviz-topics/EarthSim#77]
Build HPC-installable conda or hashdist packages making it simpler to install simulation code like ADH on ERDC HPC systems

**Comment by jbednar** [comment]
Need to ensure that all EarthSim packages are HPC installable.

**Comment by philippjfr** [comment]
I believe this was completed, and should be re-raised either as part of the new work or as a separate public issue.
