### ISSUE TITLE
Roadmap: Task 6b: Optimize rendering of meshes and polygons

### ISSUE THREAD

**Issue by jlstevens** [pyviz-topics/EarthSim#85]
Speed up rendering of unstructured meshes and polygons

**Comment by philippjfr** [comment]
This was implemented by enabling dynamic downsampling of paths/polygons in https://github.com/pyviz/geoviews/pull/282, through enhanced line/wiremesh rendering in https://github.com/pyviz/datashader/pull/694 and through dask trimesh support in https://github.com/pyviz/datashader/pull/696.
