### ISSUE TITLE
Roadmap:Task 6c: Support spatial acceleration structures

### ISSUE THREAD

**Issue by jlstevens** [pyviz-topics/EarthSim#86]
Support data with RTree/Quadtree-type spatial bounding, to work efficiently with spatial subsets of large datasets

**Comment by philippjfr** [comment]
This was delivered through datashader work on spatial indexing in https://github.com/pyviz/datashader/pull/702 and https://github.com/pyviz/datashader/pull/706

**Comment by kcpevey** [comment]
@philippjfr Is this functionality that we now get for 'free' or do I need to trigger it with a keyword in the render?

**Comment by philippjfr** [comment]
You get it for free, note that it's not yet handled for many types, specifically we have not solved the issue for trimeshes.

**Comment by kcpevey** [comment]
Ok yeah I was just looking back through those PRs. I'll have to spend some time testing that out. Trimeshes are dask supported now - that supports initial rendering, while trimesh/datashade improvements would support faster reactivity. Is that correct?
